/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exerciciosjava_06;

import java.awt.Font;

/**
 *
 * @author alifi
 */
public class JogoDoGenio extends javax.swing.JFrame {

    /**
     * Creates new form OperadoresLogicos
     */
    public JogoDoGenio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGenio = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        spnNumero = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Genio-Aladdin-png.png"))); // NOI18N
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        lblTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTexto.setText("Escolha um número");
        getContentPane().add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 160, -1));

        lblBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao.png"))); // NOI18N
        getContentPane().add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -20, 450, 300));

        jLabel1.setText("Escolha um número");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        btnVerificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerificar.setText("Verificar...");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        spnNumero.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(spnNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 60, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed

        double n = 1 + Math.random() * (6-1);
        int valor = (int) n;
        String frase = "";
        
        int num = Integer.parseInt(spnNumero.getValue().toString());
        
        if(valor == num){
            frase = "<html> ACERTOU!! </html>";
        }else{
            frase = "<html> Errou! Pensei no número " + valor + "</html>";
        }
        lblTexto.setFont(new Font ("Arial Brack", Font.PLAIN, 18));
        lblTexto.setText(frase);



    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDoGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDoGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDoGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDoGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDoGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JSpinner spnNumero;
    // End of variables declaration//GEN-END:variables
}
